# 数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ssmbuild?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver


# 整合 MyBatis
mybatis:
  type-aliases-package: com.zjp.pojo
  mapper-locations: classpath:com/zjp/dao/*.xml
# Swagger 是否启用
springfox:
  documentation:
    swagger-ui:
      enabled: true
